name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ================= Backend Build ===================
      - name: Build backend Docker image
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_USERNAME }}/myapp:latest \
            backend

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # ================= Frontend Build ==================
      - name: Build frontend Docker image
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_USERNAME }}/agentic-logistics-frontend:latest \
            agentic-logistics-frontend

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/agentic-logistics-frontend:latest

  deploy_production:
    needs: build_and_push_images
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/agentic-logistics-frontend:latest
            docker stop myapp-backend || true
            docker rm myapp-backend || true
            docker run -d --restart always \
              -p 8000:8000 \
              --name myapp-backend \
              ${{ secrets.DOCKER_USERNAME }}/myapp:latest

            docker stop agentic-frontend || true
            docker rm agentic-frontend || true
            docker run -d --restart always \
              -p 80:80 \
              --name agentic-frontend \
              ${{ secrets.DOCKER_USERNAME }}/agentic-logistics-frontend:latest
